#!/usr/bin/python
"""takes a valkue and returns the swuared value
   added one **more line here
"""
def my_square(y):
      return (y ** 2)

def my_square2(x):
         """ uses the * operator to calculate square
         """
     return (x ** x)

print (my_square(100))
print (my_square2(100))
